src/Entity/OrderItem.php
<?php

namespace App\Entity;

use App\Repository\OrderItemRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OrderItemRepository::class)
 */
class OrderItem
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\GreaterThanOrEqual(1)
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Order::class, inversedBy="items")
     * @ORM\JoinColumn(nullable=false)
     */
    private $orderRef;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getOrderRef(): ?Order
    {
        return $this->orderRef;
    }

    public function setOrderRef(?Order $orderRef): self
    {
        $this->orderRef = $orderRef;

        return $this;
    }
    
    public function equals(OrderItem $item): bool
    {
        return $this->getProduct()->getId() === $item->getProduct()->getId();
    }
    
    public function getTotal()
    {
        return $this->getProduct()->getPrice() * $this->getQuantity();
  
    }
}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Form\EventListener\ClearCartListener;
use App\Form\EventListener\RemoveCartItemListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('items',CollectionType::class,[
                'entry_type' => CartItemType::class
            ])
            ->add('save',SubmitType::class)
            ->add('clear',SubmitType::class)
        ;

        $builder->addEventSubscriber(new RemoveCartItemListener());
        $builder->addEventSubscriber(new ClearCartListener());
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Form\CartType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\Order\CartManager;

class CartController extends AbstractController
{
    /**
     * @Route("/cart", name="cart")
     */
    public function index(CartManager $cartManager,Request $request): Response
    {
        $cart = $cartManager->getCurrentCart();
        
        //var_dump($cart->getTotal());exit();
        $form = $this->createForm(CartType::class,$cart);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $cart->setUpdatedAt(new \DateTime());
            $cartManager->save($cart);

            return $this->redirectToRoute('cart');
        }
        return $this->render('cart/index.html.twig', [
            'cart' => $cart,
            'form' => $form->createView(),
        ]);
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cart{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1>Your Cart</h1>
    {% if cart.items.count > 0 %}
        <div class="row mt-4">
            <div class="col-md-8">
                {{ form_start(form) }}
                <div class="card-header bg-dark text-white d-flex">
                    <h5>Items</h5>
                    <div class="ml-auto">
                        {{ form_widget(form.save,{'attr':{'class':'btn btn-warning'}}) }}
                        {{ form_widget(form.clear,{'attr':{'class':'btn btn-light'}}) }}
                    </div>
                </div>
                <ul class="list-group list-group-flash">
                    {% for item in form.items %}
                    <li class="list-group-item d-flex">
                        <div class="flex-fill mr-2">
                            <img src="https://via.placeholder.com/200x150" width="64" alt="Product Item">
                        </div>
                        <div class="flex-fill mr-2">
                            <h5 class="mt-0 mb-0">{{ item.vars.data.product.name }}</h5>
                            <small>{{ item.vars.data.product.description[:50] }}</small>
                            <div class="form-inline mt-2">
                                <div class="form-group mb-0 mr-2">
                                    {{ form_widget(item.quantity,{'attr':{'class':'form-control form-control-sm' ~ (item.quantity.vars.valid ? '' : 'is-valid')}}) }}
                                    <div class="invalid-feedback">
                                        {{ form_errors(item.quantity) }}
                                    </div>
                                </div>
                                {{ form_widget(item.remove,{'attr':{'class':'btn btn-dark btn-sm'}}) }}
                            </div>

                        </div>
                        <div class="flex-fill mr-2 text-right">
                            <b>{{ item.vars.data.product.price }}₺</b>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {{ form_end(form,{'render_res':false}) }}
        </div>
            <div class="col-md-4">
                <div class="card mt-4 mt-md-0">
                    <h5 class="card-header bg-dark text-white">Summary</h5>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between">
                            <div><b>Total</b></div>

                            <span><b>{{ cart.total }}₺</b></span>
                        </li>
                    </ul>
                    <div class="card-body">
                        <a href="#" class="btn btn-warning w-100">checkout</a>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
    <div class="alert alert-info">
        Your cart is empty.Go to the <a href="{{ path('home') }}">Product list</a>.
    </div>
    {% endif %}
</div>
{% endblock %}